### PR TITLE
Add tagFilter option.

### PR DESCRIPTION
**Pull request by mvanbutselaar**

### CODE REVIEW

**Comment by wvbe** [comment]
Hey @mvanbutselaar, thanks for the PR. This feature lets you skip certain elements before they're even raised to a DOM. I presume you've used this to parse large files of which a clear portion was not relevant.

I've only two questions;
- How do you feel about running an XPath on a half-finished DOM (the `contextNode` argument of `tagFilter`)? eg. using `child::*` or `following-sibling::*` on the context node may give unexpected results
- How do you feel about applying a similar filter on other nodes, such as CData or attribute nodes?

**Comment by DrRataplan** [comment]
Cool idea to use XPaths here, but I agree with Wybe, it can be finicky if you use the wrong path expressions. However, there is something called XPath streaming: https://www.saxonica.com/documentation9.5/sourcedocs/streaming/streamable-xpath.html where you do not keep the document in memory when you do not need to.

You could use this. The domFacade argument of evaluateXPath in FontoXPath allows you to intercept all DOM calls. You could write a streaming XPath processor with this.

Example: child axis

```javascript
domFacade#getFirstChild (node) {
  if (streamer.currentNode !== node) {
    // Out of sync, old node is already passed
  }

  const nextChildNodeName = streamer.readNextNode();
  if (!nextChild) {
    return null;
  }

  // To allow implementation of the parent axis
  streamer.ancestry.push(streamer.currentNode)

  streamer.currentNode = {
    localName: nextChildNodeName,
    // etc for all other properties that are on a dom,
    //   except for the DOM relations like children, parent, attributes, data
  }
}
```

This will still disallow backwards traversal (`preceding` / `preceding-sibling`) and a bunch of complex queries, but it will allow `child` queries, `ancestor`-queries and `following-sibling`-queries with minimal memory consumption.

**Comment by mvanbutselaar** [comment]
I agree that you can get unexpected results when querying any descendants of the contextNode. The main reason for this feature, which was used for processing large files with a lot of irrelevant metadata in order to keep memory usage down. And this case only covered skipping a node and all of it's descendants, based on the tag itself and/or its parent/ancestors.

Even though it has some caveats, it did provide some use when handling large files. We could add some more documentation to highlight the limitations. I leave it up to you to decide if it is a feature that should be added... or not.

Alternatively, is there a way to force the use of a specific domFacade (or pass it into the callback so it can be used in FontoXPath functions), and let that domFacade just throw an error when trying to access childNodes/firstNode/lastNode/etc of the contextNode? That might make the limitations more clear, instead of trying to use an XPath expression on some childNodes that might give unexpected results.

**Comment by wvbe** [comment]
Hey @mvanbutselaar, sorry for having this PR remain open for so long. I think the idea of a `domFacade` that would make the culled DOM more visible is a good idea. However, I also get the sense that you don't need this particular change any more, the large files (presumably Fonto's Confluence exports to XML) are handled by now.

I'll close the PR here but feel free to re-open it again if you'd like to tinker on that domFacade more and integrate still.

Thanks for PR'ing!

**Pull request closed without merging**
